ResultsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Results-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST

    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: questionId
        AttributeType: S

    KeySchema:
      - AttributeName: id
        KeyType: HASH

    GlobalSecondaryIndexes:
      - IndexName: questionId
        KeySchema:
          - AttributeName: questionId
            KeyType: HASH
        Projection:
          ProjectionType: ALL
