service: butterfly-demo

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-esbuild
  - serverless-iam-roles-per-function

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  stage: ${opt:stage, "dev"} #local or dev (AWS)
  region: 'us-east-2'

  environment:
    ENV: ${self:provider.stage}
    COMPANIES_TABLE_NAME: ${self:custom.CompaniesTable.name}
    QUESTIONS_TABLE_NAME: ${self:custom.QuestionsTable.name}
    RESULTS_TABLE_NAME: ${self:custom.ResultsTable.name}
    COMPANIES_TABLE_NAME_LOCAL: Companies-local
    QUESTIONS_TABLE_NAME_LOCAL: Questions-local
    RESULTS_TABLE_NAME_LOCAL: Results-local

  iam:
    role:
      statements:
        - ${file(resources/iam/CompaniesTable.yml):CompaniesTable}
        - ${file(resources/iam/QuestionsTable.yml):QuestionsTable}
        - ${file(resources/iam/ResultsTable.yml):ResultsTable}

resources:
  - ${file(resources/database/Model.yml)}

functions:
  - ${file(resources/functions/CompaniesApi.yml)}
  - ${file(resources/functions/QuestionsApi.yml)}
  - ${file(resources/functions/ResultsApi.yml)}

custom:
  CompaniesTable:
    name: !Ref CompaniesTable
    arn: !GetAtt CompaniesTable.Arn
  QuestionsTable:
    name: !Ref QuestionsTable
    arn: !GetAtt QuestionsTable.Arn
  ResultsTable:
    name: !Ref ResultsTable
    arn: !GetAtt ResultsTable.Arn
  serverless-offline:
    httpPort: 8080

  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      seedPath: /seeds/db-seed.json
    stages:
      - ${self:provider.stage}
