service: butterfly-demo

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-esbuild
  - serverless-iam-roles-per-function

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  stage: ${opt:stage, "dev"}
  region: 'us-east-2'

  environment:
    COMPANIES_TABLE_NAME: ${self:custom.CompaniesTable.name}
    QUESTIONS_TABLE_NAME: ${self:custom.QuestionsTable.name}
    RESULTS_TABLE_NAME: ${self:custom.ResultsTable.name}
  iam:
    role:
      statements:
        - ${file(resources/iam/CompaniesTable.yml):CompaniesTable}
        - ${file(resources/iam/QuestionsTable.yml):QuestionsTable}
        - ${file(resources/iam/ResultsTable.yml):ResultsTable}

resources:
  - ${file(resources/database/Model.yml)}

custom:
  CompaniesTable:
    name: !Ref CompaniesTable
    arn: !GetAtt CompaniesTable.Arn
  QuestionsTable:
    name: !Ref QuestionsTable
    arn: !GetAtt QuestionsTable.Arn
  ResultsTable:
    name: !Ref ResultsTable
    arn: !GetAtt ResultsTable.Arn

  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      seedPath: /seeds/db-seed.json
    stages:
      - ${self:provider.stage}
